name: CI - Lint and Test

on:
  push:
    branches:
      - main
      - develop
      - "feature/*"
  pull_request:
    branches:
      - main
      - develop

jobs:
  # Backend job
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Set up the environment for testing
        run: |
          cp .env.testing .env
          php artisan key:generate
          php artisan migrate

      - name: Run Laravel tests
        run: vendor/bin/phpunit

      # - name: Run backend linter (Pint)
      #   run: cd backend && ./vendor/bin/pint

  # Frontend job
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      # - name: Run frontend linter (ESLint)
      # run: cd frontend && npm run lint
      # run: cd frontend

      - name: Run frontend tests (Jest)
        run: cd frontend && npm test
